{% set name = "loinchpo" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f082e7b609c727c3902554b89e7cda0a0aed1f25142eebed5cc57bd866ffabf2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - click
    - pandas

test:
  requires:
    - ddt
    - setuptools
    - pandas
  imports:
    - loinchpo.model
    - loinchpo.io
    - loinchpo.error
    - loinchpo

about:
  home: https://github.com/TheJacksonLaboratory/loinchpo
  summary: 'Simple & Efficient Loinc To HPO for Python'
  license: GPL-3.0
  license_file: LICENSE.txt
  description: |
    loinchpo is a simple and efficient library for mapping loinc test results
    to hpo terms. Pure python, 3.5+

extra:
  recipe-maintainers:
    - iimpulse
