name: Sphinx Documentation
on:
  push:
    branches: [ enhancement/documentation ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@enhancement/documentation
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: install
      run: pip3 install sphinx sphinx-rtd-theme recommonmark click ddt pandas

    - name: Build documentation.
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        sphinx-apidoc -f -o docs/source loinchpo **/tests/
        cd docs/
        sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/

    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
